echo "========= Lazypic Alias ========="
echo "    blender : run blender"
echo "     natron : run natron"
echo " renderfarm : sheep it renderfarm"
echo "   homepage : open homepage"
echo "     github : open github"
echo "googledrive : open googledrive"
echo "optimizilla : image opimization"
echo "     update : update setting"
echo "================================="

