echo "======= Lazypic Alias ========"
echo "blender : run blender"
echo "wiki : open wiki"
echo "chat : chatting server"
echo "homepage : open homepage"
echo "github : open github"
echo "googledrive : open googledrive"
echo "update : update setting"
echo "=============================="

